service: serverless-test-pzmsmz

provider:
  name: aws
  runtime: nodejs8.10

package:
  individually: true

functions:
  helloWorld:
    handler: frontend/func1/handler.hello

  helloWorld2:
    handler: backend/func2/handler.hello2
