codecov:
  notify:
    after_n_builds: 2
    wait_for_ci: false
  require_ci_to_pass: false

comment:
  after_n_builds: 2

coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 10
    project:
      default:
        target: auto
        threshold: 1
