# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: /
    labels:
      - maintenance
      - github_actions
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - directory: /
    labels:
      - maintenance
      - javascript
    open-pull-requests-limit: 5
    package-ecosystem: npm
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - directory: /
    ignore:
      - dependency-name: boto3
      - dependency-name: boto3-stubs
      - dependency-name: botocore
      - dependency-name: mypy-boto3
    labels:
      - dependencies
      - poetry
      - python
    open-pull-requests-limit: 5
    package-ecosystem: pip
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
    versioning-strategy: lockfile-only
  - allow:
      - dependency-name: boto3
      - dependency-name: boto3-stubs
      - dependency-name: botocore
      - dependency-name: mypy-boto3
    directory: /
    labels:
      - dependencies
      - poetry
      - python
    open-pull-requests-limit: 10
    package-ecosystem: pip
    schedule:
      day: monday
      interval: weekly
      time: "08:00"
      timezone: America/New_York
    versioning-strategy: lockfile-only
