# https://github.com/release-drafter/release-drafter
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🧶 Dependencies
    labels:
      - dependencies
  - title: 📖 Doc Updates
    labels:
      - documentation
  - title: 🧰 Maintenance
    label: maintenance
category-template: |
  ### $TITLE
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
  - skip-changelog
  - release
name-template: v$RESOLVED_VERSION
sort-direction: ascending
tag-template: v$RESOLVED_VERSION
template: |
  ## What Changed

  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
