default_language_version:
  python: python3.7

minimum_pre_commit_version: "2.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - "--unsafe"  # needed for parsing CFN

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        exclude: ^integration_tests
