default_language_version:
  python: python3.7

minimum_pre_commit_version: "2.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
