minimum_pre_commit_version: 2.6.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe  # needed for parsing CFN
      - id: end-of-file-fixer
        exclude: .*\.json-result
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.gitignore|
            \.vscode/dictionaries/.*\.txt|
            MANIFEST.in
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.vscode/.*\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            (.*)?(cdk|tsconfig|tslint).json
          )$
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.1.0
    hooks:
      - id: yamlfmt
        args: [--implicit_start, --mapping, '2', --offset, '2', --sequence, '4']
        files: |
          (?x)^(
            \.github/(?!dependabot).*\.(yaml|yml)|
            \.markdownlint.yml|
            \.pre-commit-config.yaml|
            \.readthedocs.yml|
            buildspec.yml
          )$
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args:
          - --color
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - flake8-print
          - flake8-use-fstring
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
