namespace: ${namespace}
cfngin_bucket: ""

sys_path: ./../../../

tags:
  Environment: ${environment}
  Namespace: ${namespace}
  Repository: https://github.com/rackspace/runway

stacks:
  - name: cfngin-bucket
    class_path: blueprints.CfnginBucket
    variables:
      BucketName: runway-testing-alt-lab-cfngin-bucket-${region}
