name: Test Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/blueprints/admin_user.py
      - infrastructure/blueprints/prevent_privilege_escalation.py
      - infrastructure/blueprints/test_runner_boundary.py
      - infrastructure/test/common/**
  workflow_dispatch:

concurrency: infrastructure-test
defaults:
  run:
    shell: bash
env:
  PIPENV_NOSPIN: true
  PIPENV_VENV_IN_PROJECT: true
  PIPENV_YES: true

jobs:
  deploy:
    name: Deploy
    strategy:
      fail-fast: true
      matrix:  # only one setting for each, provides an easy place to update
        python-version: [3.8]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Pip Cache (ubuntu)  # no supported by workflow_dispatch
      #   uses: actions/cache@v1
      #   if: matrix.os == 'ubuntu-18.04'
      #   with:
      #     path:  ~/.cache/pip
      #     key: ${{ matrix.os }}-pip-${{ matrix.python-version }}
      #     restore-keys: |
      #       ${{ matrix.os }}-pip-${{ matrix.python-version }}
      - name: Install Global Python Packages
        run: |
          python -m pip install --upgrade pip setuptools
          pip install "virtualenv==16.7.9" "pipenv==2018.11.26"
      - name: Setup Python Virtual Environment
        run: pipenv sync --dev
      - name: runway plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          DEPLOY_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
        run: make plan test
        working-directory: infrastructure/
      - name: runway deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          DEPLOY_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
        run: make deploy test
        working-directory: infrastructure/
