name: PR


on:
  pull_request:


jobs:
  branch-name:
    name: Enforce Branch Name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0  # cspell:ignore deepakputhraya
        with:
          regex: ([a-z])+\/([a-zA-Z0-9\-\_])+
          allowed_prefixes: bugfix,chore,depend,dependabot,docs,feat,feature,fix,hotfix,maint,maintain,maintenance,release
          ignore: develop,master,release,v0_47_fixes
  label-pr:
    name: Label PR
    # Skip running the job from forks.
    if: github.repository == 'onicagroup/runway' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.16.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
