name: Publish Release


on:
  release:
    types:
      - published

env:
  AWS_DEFAULT_REGION: us-east-1


jobs:
  build-pyinstaller-onefile:
    name: Pyinstaller "One File" Build
    strategy:
      fail-fast: true
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    env:
      OS_NAME: ${{ matrix.os }}
      # pydantic binary causes a recursion error
      # https://github.com/pyinstaller/pyinstaller/issues/4406
      PIP_NO_BINARY: pydantic
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install Dependencies (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: sudo apt-get update && sudo apt-get install sed -y
      - name: Install Dependencies (windows)
        if: matrix.os == 'windows-latest'
        run: choco install make sed
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.0.11
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: runner.os != 'Windows' && steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - run: poetry install --extras docs -vv
      - name: Run Build
        run: make build-pyinstaller-file
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pyinstaller-onefile-${{ matrix.os }}
          path: artifacts
  build-pyinstaller-onefolder:
    name: Pyinstaller "One Folder" Build
    strategy:
      fail-fast: true
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    env:
      OS_NAME: ${{ matrix.os }}
      # pydantic binary causes a recursion error
      # https://github.com/pyinstaller/pyinstaller/issues/4406
      PIP_NO_BINARY: pydantic
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install Dependencies (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: sudo apt-get update && sudo apt-get install sed -y
      - name: Install Dependencies (windows)
        if: matrix.os == 'windows-latest'
        run: choco install make sed
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.0.11
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: runner.os != 'Windows' && steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - run: poetry install --extras docs -vv
      - name: Run Build
        run: make build-pyinstaller-folder
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pyinstaller-onefolder-${{ matrix.os }}
          path: artifacts
  build-npm:
    name: Build npm 📦
    needs:
      - build-pyinstaller-onefolder
    env:
      NODE_VERSION: 12
      NPM_PACKAGE_NAME: '@onica/runway'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          scope: '@onica'
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install Dependencies (ubuntu)
        run: sudo apt-get update && sudo apt-get install sed tree -y
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.0.11
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: runner.os != 'Windows' && steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - run: poetry install --extras docs -vv
      - name: Download Artifacts (macOS)
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-onefolder-macos-10.15
          path: artifacts
      - name: Download Artifacts (ubuntu)
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-onefolder-ubuntu-18.04
          path: artifacts
      - name: Download Artifacts (windows)
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-onefolder-windows-latest
          path: artifacts
      - name: List Artifacts
        run: tree artifacts/
      - name: npm Prep
        run: make npm-prep
      - name: npm pack
        run: |
          npm pack
          rm -rf artifacts && mkdir -p artifacts
          find . -name 'onica-runway-*.*.*.tgz' -exec mv {} artifacts/ \;
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-pack
          path: artifacts
  publish-npm:
    name: Publish 📦 To npm
    needs:
      - build-npm
    env:
      CI: true
      NODE_VERSION: 12
      NPM_PACKAGE_NAME: '@onica/runway'
      NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: npm-pack
          path: artifacts
      - name: Publish Distribution 📦 to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}
        run: |
          find ./artifacts -name 'onica-runway-*.*.*.tgz' -exec npm publish --access public {} +
  build-pypi:
    name: Build PyPi 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: 3.8
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install Dependencies (ubuntu)
        run: sudo apt-get update && sudo apt-get install sed -y
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.0.11
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: runner.os != 'Windows' && steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - run: poetry install --extras docs -vv
      - name: Run Build
        run: make build
      - name: Upload Distribution Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pypi-dist
          path: dist
  publish-pypi:
    name: Publish 📦 To PyPI
    needs:
      - build-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Distribution Artifact
        uses: actions/download-artifact@v3
        with:
          name: pypi-dist
          path: dist
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.0.11
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - run: poetry install --extras docs -vv
      - run: make version
      - name: Publish Distribution 📦 to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_password }}
        run: poetry publish
  publish-s3:
    name: Publish 📦 To S3
    needs:
      - build-pyinstaller-onefile
    env:
      AWS_DEFAULT_REGION: us-west-2
      AWS_S3_BUCKET: common-runway-assets-bucket83908e77-u2xp1bj1tuhp
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: 3.8
      - name: Download Artifacts (macOS)
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-onefile-macos-10.15
          path: artifacts
      - name: Download Artifacts (ubuntu)
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-onefile-ubuntu-18.04
          path: artifacts
      - name: Download Artifacts (windows)
        uses: actions/download-artifact@v3
        with:
          name: pyinstaller-onefile-windows-latest
          path: artifacts
      - name: Install AWS CLI & Upload 📦
        run: |
          pip install "awscli~=1.18.19"
          aws s3 cp artifacts s3://$AWS_S3_BUCKET/runway/ --recursive --acl public-read
  update-urlshortener:
    name: Update URL Shortener
    needs:
      - publish-s3
    env:
      BUCKET_NAME: common-runway-assets-bucket83908e77-u2xp1bj1tuhp
      BUCKET_REGION: us-west-2
      TABLE: onica-urlshortener-prod
      TABLE_REGION: us-east-1
      VERSION: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v3.0.11
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure Cache Is Healthy
        if: runner.os != 'Windows' && steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - run: poetry install --extras docs -vv
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: us-east-1
      - name: Run Script
        working-directory: .github/scripts/urlshortener
        run: |
          poetry run python update_urls.py \
            --bucket-name $BUCKET_NAME \
            --bucket-region $BUCKET_REGION \
            --table $TABLE \
            --table-region $TABLE_REGION \
            --version $VERSION \
            --latest
