name: Publish Release


on:
  release:
    types:
      - published

env:
  AWS_DEFAULT_REGION: us-east-1


jobs:
  build-pyinstaller-onefile:
    name: Pyinstaller "One File" Build
    strategy:
      fail-fast: true
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    env:
      OS_NAME: ${{ matrix.os }}
      # pydantic binary causes a recursion error
      # https://github.com/pyinstaller/pyinstaller/issues/4406
      PIP_NO_BINARY: pydantic
    steps:
      - name: ⤵️ Check out code from GitHub (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-plugins: poetry-dynamic-versioning
          python-version: ${{ matrix.python-version }}
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: ⤵️ Install Dependencies (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: sudo apt-get update && sudo apt-get install sed -y
      - name: ⤵️ Install Dependencies (windows)
        if: matrix.os == 'windows-latest'
        run: choco install make sed
      - name: 👷 Build
        run: make build-pyinstaller-file
      - name: ⤴️ Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-onefile-${{ matrix.os }}
          path: artifacts
  build-pyinstaller-onefolder:
    name: Pyinstaller "One Folder" Build
    strategy:
      fail-fast: true
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    env:
      OS_NAME: ${{ matrix.os }}
      # pydantic binary causes a recursion error
      # https://github.com/pyinstaller/pyinstaller/issues/4406
      PIP_NO_BINARY: pydantic
    steps:
      - name: ⤵️ Check out code from GitHub (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-plugins: poetry-dynamic-versioning
          python-version: ${{ matrix.python-version }}
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: ⤵️ Install Dependencies (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: sudo apt-get update && sudo apt-get install sed -y
      - name: ⤵️ Install Dependencies (windows)
        if: matrix.os == 'windows-latest'
        run: choco install make sed
      - name: 👷 Build
        run: make build-pyinstaller-folder
      - name: ⤴️ Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-onefolder-${{ matrix.os }}
          path: artifacts
  build-npm:
    name: Build npm 📦
    needs:
      - build-pyinstaller-onefolder
    env:
      NODE_VERSION: 20
      NPM_PACKAGE_NAME: '@onica/runway'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⤵️ Check out code from GitHub (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-plugins: poetry-dynamic-versioning
          python-version: ${{ matrix.python-version }}
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          scope: '@onica'
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: ⤵️ Install Dependencies (ubuntu)
        run: sudo apt-get update && sudo apt-get install sed tree -y
      - name: ⤵️ Download distribution artifacts (macOS)
        uses: actions/download-artifact@v4
        with:
          name: pyinstaller-onefolder-macos-12
          path: artifacts
      - name: ⤵️ Download distribution artifacts (ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: pyinstaller-onefolder-ubuntu-latest
          path: artifacts
      - name: ⤵️ Download distribution artifacts (windows)
        uses: actions/download-artifact@v4
        with:
          name: pyinstaller-onefolder-windows-latest
          path: artifacts
      - name: ℹ️ List Artifacts
        run: tree artifacts/
      - name: 👷 npm Prep
        run: make npm-prep
      - name: 👷 Build
        run: |
          npm pack
          rm -rf artifacts && mkdir -p artifacts
          find . -name 'onica-runway-*.*.*.tgz' -exec mv {} artifacts/ \;
      - name: ⤴️ Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-pack
          path: artifacts
  publish-npm:
    name: Publish 📦 To npm
    needs:
      - build-npm
    env:
      CI: true
      NODE_VERSION: 20
      NPM_PACKAGE_NAME: '@onica/runway'
      NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: ⤵️ Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-pack
          path: artifacts
      - name: 🚀 Publish Distribution 📦 to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_api_token }}
        run: |
          find ./artifacts -name 'onica-runway-*.*.*.tgz' -exec npm publish --access public {} +
  build-pypi:
    name: Build PyPi 📦
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-plugins: poetry-dynamic-versioning
      # Remove apt repos that are known to break from time to time
      # See https://github.com/actions/virtual-environments/issues/323
      - name: Remove broken apt repos (ubuntu)
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: ⤵️ Install Dependencies (ubuntu)
        run: sudo apt-get update && sudo apt-get install sed -y
      - name: 👷 Build
        run: make build
      - name: ⤴️ Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist
  publish-pypi:
    name: Publish 📦 To PyPI
    needs:
      - build-pypi
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ⤵️ Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-install: false
          poetry-plugins: poetry-dynamic-versioning
      - name: 🚀 Publish Distribution 📦 to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_password }}
        run: poetry publish
  publish-s3:
    name: Publish 📦 To S3
    needs:
      - build-pyinstaller-onefile
    env:
      AWS_DEFAULT_REGION: us-west-2
      AWS_S3_BUCKET: common-runway-assets-bucket83908e77-u2xp1bj1tuhp
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-install: false
      - name: ⤵️ Download distribution artifacts (macOS)
        uses: actions/download-artifact@v4
        with:
          name: pyinstaller-onefile-macos-12
          path: artifacts
      - name: ⤵️ Download distribution artifacts (ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: pyinstaller-onefile-ubuntu-latest
          path: artifacts
      - name: ⤵️ Download distribution artifacts (windows)
        uses: actions/download-artifact@v4
        with:
          name: pyinstaller-onefile-windows-latest
          path: artifacts
      - name: 🚀 Install AWS CLI & Upload 📦
        run: |
          pip install "awscli~=1.18.19"
          aws s3 cp artifacts s3://$AWS_S3_BUCKET/runway/ --recursive --acl public-read
  update-urlshortener:
    name: Update URL Shortener
    needs:
      - publish-s3
    env:
      BUCKET_NAME: common-runway-assets-bucket83908e77-u2xp1bj1tuhp
      BUCKET_REGION: us-west-2
      TABLE: onica-urlshortener-prod
      TABLE_REGION: us-east-1
      VERSION: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🏗 Setup Python
        uses: finleyfamily/action-setup-python@v1.0.0
        with:
          poetry-plugins: poetry-dynamic-versioning
      - name: 🏗 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: us-east-1
      - name: 🚀 Run Script
        working-directory: .github/scripts/urlshortener
        run: |
          poetry run python update_urls.py \
            --bucket-name $BUCKET_NAME \
            --bucket-region $BUCKET_REGION \
            --table $TABLE \
            --table-region $TABLE_REGION \
            --version $VERSION \
            --latest
  notify-on-publish:
    name: Notify
    needs:
      - publish-npm
      - publish-pypi
      - update-urlshortener
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@v1.0.8
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
