name: Spell Check

# There is an official action published by cSpell.
# v1.1.1 was tested but did not function as desired so we are using the CLI.

on: push


env:
  NODE_VERSION: '18'


jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: make npm-ci
      - run: make spellcheck
